src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

use App\Event\Listener\UserListener;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\EntityListeners({"App\Event\Listener\UserListener"})
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToOne(targetEntity=UserProfile::class, mappedBy="users", cascade={"persist", "remove"})
     */
    private $user_profile;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, mappedBy="favourite_to")
     */
    private $favourite_books;

    /**
     * @ORM\OneToMany(targetEntity=BookRating::class, mappedBy="users", orphanRemoval=true)
     */
    private $bookRatings;

    /**
     * @ORM\OneToMany(targetEntity=AuthorRating::class, mappedBy="users", orphanRemoval=true)
     */
    private $authorRatings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="users")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Author::class, inversedBy="favourite_to")
     */
    private $favourite_authors;

    public function __construct()
    {
        $this->votes = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->favourite_books = new ArrayCollection();
        $this->bookRatings = new ArrayCollection();
        $this->authorRatings = new ArrayCollection();
        $this->favourite_authors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserProfile(): ?UserProfile
    {
        return $this->user_profile;
    }

    public function setUserProfile(UserProfile $user_profile): self
    {
        // set the owning side of the relation if necessary
        if ($user_profile->getUsers() !== $this) {
            $user_profile->setUsers($this);
        }

        $this->user_profile = $user_profile;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getFavouriteBooks(): Collection
    {
        return $this->favourite_books;
    }

    public function addFavouriteBook(Book $favouriteBook): self
    {
        if (!$this->favourite_books->contains($favouriteBook)) {
            $this->favourite_books[] = $favouriteBook;
            $favouriteBook->addFavouriteTo($this);
        }

        return $this;
    }

    public function removeFavouriteBook(Book $favouriteBook): self
    {
        if ($this->favourite_books->removeElement($favouriteBook)) {
            $favouriteBook->removeFavouriteTo($this);
        }

        return $this;
    }

    /**
     * @return Collection|BookRating[]
     */
    public function getBookRatings(): Collection
    {
        return $this->bookRatings;
    }

    public function addBookRating(BookRating $bookRating): self
    {
        if (!$this->bookRatings->contains($bookRating)) {
            $this->bookRatings[] = $bookRating;
            $bookRating->setUsers($this);
        }

        return $this;
    }

    public function removeBookRating(BookRating $bookRating): self
    {
        if ($this->bookRatings->removeElement($bookRating)) {
            // set the owning side to null (unless already changed)
            if ($bookRating->getUsers() === $this) {
                $bookRating->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|AuthorRating[]
     */
    public function getAuthorRatings(): Collection
    {
        return $this->authorRatings;
    }

    public function addAuthorRating(AuthorRating $authorRating): self
    {
        if (!$this->authorRatings->contains($authorRating)) {
            $this->authorRatings[] = $authorRating;
            $authorRating->setUsers($this);
        }

        return $this;
    }

    public function removeAuthorRating(AuthorRating $authorRating): self
    {
        if ($this->authorRatings->removeElement($authorRating)) {
            // set the owning side to null (unless already changed)
            if ($authorRating->getUsers() === $this) {
                $authorRating->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUsers($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUsers() === $this) {
                $comment->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Author[]
     */
    public function getFavouriteAuthors(): Collection
    {
        return $this->favourite_authors;
    }

    public function addFavouriteAuthor(Author $favouriteAuthor): self
    {
        if (!$this->favourite_authors->contains($favouriteAuthor)) {
            $this->favourite_authors[] = $favouriteAuthor;
        }

        return $this;
    }

    public function removeFavouriteAuthor(Author $favouriteAuthor): self
    {
        $this->favourite_authors->removeElement($favouriteAuthor);

        return $this;
    }
}

src/Entity/UserProfile.php
<?php

namespace App\Entity;

use App\Repository\UserProfileRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserProfileRepository::class)
 */
class UserProfile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $about_me;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="user_profile", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $favourite_genres;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAboutMe(): ?string
    {
        return $this->about_me;
    }

    public function setAboutMe(?string $about_me): self
    {
        $this->about_me = $about_me;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(User $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getFavouriteGenres(): ?string
    {
        return $this->favourite_genres;
    }

    public function setFavouriteGenres(?string $favourite_genres): self
    {
        $this->favourite_genres = $favourite_genres;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\UserProfile;
use App\Entity\User;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

use App\Form\UserEditFormType;
use App\Form\UserProfileEditFormType;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/users", name="users")
     */
    public function index(): Response
    {
        $users = $this->getDoctrine()->getRepository(User::class)->findAll();
        return $this->render('user/index.html.twig', [
            'users' => $users
        ]);
    }

    /**
     * @Route("/users/{username}", name="show_user")
     */
    public function profile($username) : Response {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->findOneBy([
                'username' => $username
            ]);

        if(!$user) {
            throw  $this->createNotFoundException('User doesn\'t exist.');
        }

        $user_profile = $user->getUserProfile();

        return $this->render('user/profile.html.twig', [
            'user_profile' => $user_profile
        ]);
    }


    /**
     * @Route("/users/{username}/edit", name="edit_user")
     */
    public function edit($username, Request $request, UserPasswordEncoderInterface $passwordEncoder) : Response {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getDoctrine()->getRepository(User::class)->findOneBy([
            "username" => $username
        ]);

        if(!$user)
            throw  $this->createNotFoundException('User doesn\'t exist.');

        $currentUser = $this->getUser();
        if($user && (!in_array('ROLE_ADMIN', $currentUser->getRoles()) && $user->getUsername() != $currentUser->getUsername()))
            return $this->redirect('/users/' . $this->getUser()->getUsername() . '/edit');

        $user_response = $this->updateUser($user, $request, $passwordEncoder);
        $user_profile_response = $this->updateUserProfile($user, $request);

        if(gettype($user_response) == "string")
            return $this->redirect($user_response);
        if(gettype($user_profile_response) == "string")
            return $this->redirect($user_profile_response);

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'user_form' => $user_response->createView(),
            'user_profile_form' => $user_profile_response->createView()
        ]);
    }

    private function updateUser($user, Request $request, UserPasswordEncoderInterface $passwordEncoder) {
        $currentUser = $this->getUser();
        $user_form = $this->createForm(UserEditFormType::class, $user, ['roles' => $currentUser->getRoles()]);

        $user_form->handleRequest($request);

        if ($user_form->isSubmitted() && $user_form->isValid()) {
            $entityManager = $this
                                ->getDoctrine()
                                ->getManager();

            if (!in_array('ROLE_ADMIN', $currentUser->getRoles()) &&
                (isset($user_form['plainPassword']) && isset($user_form['passwordConfirmation']))) {
                $path = $this->checkPassword($user, $user_form['currentPassword']->getData(), $passwordEncoder);
                if($path)
                    return $path;
                else {
                    $this->updatePassword($user, $user_form, $passwordEncoder);
                }
            }

            if(in_array('ROLE_ADMIN', $currentUser->getRoles())) {
                print($user_form['roles']->getData());
                $user->setRoles([$user_form['roles']->getData()]);
            }

            $entityManager->persist($user);
            $entityManager->flush();

            $path = '/users/' . $user->getUsername();
            return $path;
        }

        return $user_form;
    }

    private function checkPassword($user, $givenPassword, $passwordEncoder) {
        if(!$passwordEncoder->isPasswordValid($user, $givenPassword)) {
            $this->addFlash('password_error', 'User\'s password and given password don\'t match');
            
            $path = '/users/' . $this->getUser()->getUsername();
            return $path;
        }
    }

    private function updateUserProfile($user, Request $request) {
        $user_profile = $user->getUserProfile();

        $oldImage = $user_profile->getImage();

        $user_profile_form = $this->createForm(UserProfileEditFormType::class, $user_profile);
        $user_profile_form->handleRequest($request);
    
        $entityManager = $this->getDoctrine()->getManager();
        if ($user_profile_form->isSubmitted() && $user_profile_form->isValid()) {
            $this->setInformation($oldImage, $user_profile_form, $user_profile);

            $entityManager->persist($user_profile);
            $entityManager->flush();

            $path = '/users/' . $user->getUsername();
            return $path;
        }

        return $user_profile_form;
    }

    private function setImage($oldImage, $user_profile_form, $user_profile) {
        $image = $user_profile_form['image']->getData();

        if($image) {
            $originalImageName = pathinfo($image, PATHINFO_FILENAME);
            $safeImageName = preg_split("/\./", $image->getClientOriginalName())[0];

            $newImageName = $safeImageName . '-' . rand(0, 100) . '.' . $image->getClientOriginalExtension();

            $image_dir = 'images/' . $this->getUser()->getUsername();
            $image->move($image_dir, $newImageName);

            $user_profile->setImage($image_dir . '/' . $newImageName);
        } else {
            $user_profile->setImage($oldImage);
        }
    }

    private function setInformation($oldImage, $user_profile_form, $user_profile) {
        $this->setImage($oldImage, $user_profile_form, $user_profile);
    
        $user_profile->setFirstName($user_profile_form['first_name']->getData());

        $user_profile->setLastName($user_profile_form['last_name']->getData());
        $user_profile->setAboutMe($user_profile_form['about_me']->getData());
        $user_profile->setFavouriteGenres($user_profile_form['favourite_genres']->getData());

        $birthday = $user_profile_form['birthday']->getData();
        $user_profile->setBirthday($birthday);
    }

    private function updatePassword($user, $user_form, $passwordEncoder) {
        $entityManager = $this->getDoctrine()
                                ->getManager();

        $user->setPassword(
            $passwordEncoder->encodePassword(
                $user,
                $user_form['plainPassword']->getData()
            )
        );

        $entityManager->persist($user);
        $entityManager->flush();
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}| Edit {{ user.username }}'s profile{% endblock %}

{% block body %}

    <h1>{{ user.username }}'s basic info</h1>
    <hr/>
    
    {% for flashError in app.flashes('password_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}

    {{ form_start(user_form) }}
        <div class="form-field disabled" disabled>
            {{ form_row(user_form.username) }}
        </div>
    {{ form_end(user_form) }}

    <hr/>

    <h1>{{user.username}}'s profile info</h1>
    <hr/>
    {{ form(user_profile_form) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}| Users{% endblock %}

{% block body %}

    {% if users|length %}
            <div class="content">
                <div class="row">
                    {% for user in users %}
                        <div class="card col-sm-4" style="margin: 10px 0 0 5px;">
                            <div class="card-body">
                                <h5 class="card-title"><a href="{{ path('show_user', { 'username': user.username }) }}">{{ user.username }}</a></h5>

                                {% if user.userProfile.image %}
                                    <img src="{{ asset(user.userProfile.image) }}" width="50%" />
                                {% else %}
                                    <img src="{{ asset('/images/default/default.jpg') }}" width="50%" />
                                {% endif %}
                                <br/>
                            <br/>
                            <hr/>
                            {{ user.favouriteBooks|length}} liked books <br/>
                            {{ user.favouriteAuthors|length}} liked authors
                            </div>
                        </div>
                    {% endfor %}
            </div>
        </div>
    {% endif %}

{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}| {{ user_profile.users.username }}'s profile{% endblock %}

{% block body %}
<div>
    <h1>{{ user_profile.users.username }}'s profile</h1>
    {% if app.user and app.user.username == user_profile.users.username or app.user.roles|first == 'ROLE_ADMIN' %}
        <a href="/users/{{ user_profile.users.username}}/edit" class="btn btn-primary btn-sm">Edit</a>
    {% endif %}

    {% if user_profile.users.roles|first == 'ROLE_ADMIN' %}
        <span class="badge bg-danger" role="alert">ADMIN</span>
    {% else %}
        <span class="badge bg-info text-dark">USER</span>
    {% endif %}
</div>
<hr/>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                {% if user_profile.image != null %}
                    <img src="/{{ user_profile.image }}" width="50%" />
                {% else %} 
                    <img src="{{ asset('images/default/default.jpg') }}" width="50%" />
                {% endif %}
            </div>
            <div class="col-md-6">
                {{ user_profile.aboutMe }} 
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-sm-6">
                        <strong>First name: </strong>
                    </div>
                    <div class="col-md-6">
                        {{ user_profile.firstName }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong>Last name: </strong>
                    </div>
                    <div class="col-md-6">
                        {{ user_profile.lastName }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong>Birthday: </strong>
                    </div>
                    <div class="col-md-6">
                        {% set birthday = user_profile.birthday|format('m-d') %}
                        {% set current = date()|date('m-d') %}

                        {{ birthday }}
                        {% if birthday and birthday == current %}
                            <img src="{{ asset('/images/default/birthday.png') }}" width="20%" title="Happy Birthday!" />
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            {% set favourite_books = user_profile.users.favouriteBooks %}

            {% if favourite_books|length %}
                <div class="col-sm-3">
                    <hr/>
                </div>
                <div class="col">
                    <h1>{{ user_profile.users.username }}'s favourite books</h1>
                </div>
                <div class="col-sm-2">
                    <hr/>
                </div>
                <div class="row">
                    {% for book in favourite_books %}
                        <div class="card col-sm-4" style="margin: 10px 0 0 5px;">
                          <div class="card-body">
                            <h5 class="card-title"><a href="{{ path('show_book', { 'id': book.id }) }}">{{ book.name }}</a></h5>
                            {% if book.cover %}
                                <img src="{{ asset(book.cover) }}" width="50%" />
                            {% else %}
                                <img src="{{ asset('/images/default/book.png') }}" width="50%" />
                            {% endif %}
                            <br/><br/>
                            <h5><a href="{{ path('show_genre', {'genre': book.genre.name}) }}" class="btn btn-primary btn-sm">{{ book.genre.name }}</a></h5>
                            {{ book.description|slice(0, 100)}}
                            <hr/>
                            <h6 class="card-subtitle mb-2 text-muted">Written by <a href="/authors/{{book.author.id}}">{{ book.author.name }}</a></h6>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <br/>
    <div class="row">
            {% set favourite_authors = user_profile.users.favouriteAuthors %}

            {% if favourite_authors|length %}
                <div class="col-sm-3">
                    <hr/>
                </div>
                <div class="col">
                    <h1>{{ user_profile.users.username }}'s favourite authors</h1>
                </div>
                <div class="col-sm-2">
                    <hr/>
                </div>
                <div class="row">
                    {% for author in favourite_authors %}
                        <div class="card col-sm-4" style="margin: 10px 0 0 5px;">
                            <div class="card-body">
                                <h5 class="card-title"><a href="{{ path('show_author', { 'id': author.id }) }}">{{ author.name }}</a></h5>

                                {% if author.image %}
                                    <img src="{{ asset(author.image) }}" width="50%" />
                                {% else %}
                                    <img src="{{ asset('/images/default/author.png') }}" width="50%" />
                                {% endif %}
                                <br/>
                            {{ author.biography|slice(0, 50)}}
                            <br/>
                            <hr/>
                            {{ author.books|length}} books
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}